// Dependency-free browser integration smoke test. Uses an isolated, disposable Edge profile.
// Run with Node 22+ on Windows: node tools/test_browser.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const net = require('node:net');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
const root = path.resolve(__dirname, '..');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
async function port() {
  const server = net.createServer();
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const value = server.address().port;
  await new Promise(resolve => server.close(resolve));
  return value;
}

(async () => {
  const edge = process.env.EDGE_PATH || 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
  assert.ok(fs.existsSync(edge), 'Set EDGE_PATH to a Chromium browser executable');
  const server = http.createServer((req, res) => {
    const filename = path.resolve(root, '.' + new URL(req.url, 'http://localhost').pathname);
    if (!filename.startsWith(root + path.sep)) { res.writeHead(403).end(); return; }
    fs.readFile(filename, (error, data) => {
      if (error) { res.writeHead(404).end(); return; }
      const mime = { '.js': 'text/javascript', '.css': 'text/css', '.html': 'text/html', '.png': 'image/png' };
      res.setHeader('Content-Type', mime[path.extname(filename)] || 'application/octet-stream');
      res.end(data);
    });
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'kimetsu-browser-test-'));
  const debugPort = await port();
  const browser = spawn(edge, ['--headless=new', '--no-sandbox', '--disable-gpu', '--no-first-run', '--no-default-browser-check',
    '--disable-background-networking', '--remote-debugging-port=' + debugPort, '--user-data-dir=' + profile,
    '--window-size=1280,1000', 'about:blank'], { windowsHide: true, stdio: 'ignore' });
  let socket;
  let call;
  try {
    let version;
    for (let i = 0; i < 100; i++) {
      try { version = await (await fetch('http://127.0.0.1:' + debugPort + '/json/version')).json(); break; }
      catch { await pause(100); }
    }
    assert.ok(version, 'browser did not start');
    socket = new WebSocket(version.webSocketDebuggerUrl);
    await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; });
    let id = 0;
    const pending = new Map();
    const errors = [];
    socket.onmessage = event => {
      const message = JSON.parse(event.data);
      if (message.method === 'Runtime.exceptionThrown') errors.push(message.params.exceptionDetails.exception?.description || message.params.exceptionDetails.text);
      if (pending.has(message.id)) {
        const { resolve, reject, timeout } = pending.get(message.id);
        clearTimeout(timeout); pending.delete(message.id);
        if (message.error) reject(Error(JSON.stringify(message.error))); else resolve(message.result);
      }
    };
    call = (method, params = {}, sessionId) => new Promise((resolve, reject) => {
      const requestId = ++id;
      const timeout = setTimeout(() => { pending.delete(requestId); reject(Error('Timed out: ' + method)); }, 30000);
      pending.set(requestId, { resolve, reject, timeout });
      socket.send(JSON.stringify({ id: requestId, method, params, sessionId }));
    });
    const { targetId } = await call('Target.createTarget', { url: 'about:blank' });
    const { sessionId } = await call('Target.attachToTarget', { targetId, flatten: true });
    const page = (method, params) => call(method, params, sessionId);
    const evaluate = async expression => {
      const result = await page('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true });
      if (result.exceptionDetails) throw Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text);
      return result.result.value;
    };
    const checkDialogTheme = async (selector, dark) => evaluate('(' + (async function(selector, dark) {
      if (Engine.isLightsOff() !== dark) Engine.turnLightsOff();
      const panel = document.querySelector(selector);
      const expected = dark ? 'rgb(39, 40, 35)' : 'rgb(255, 255, 255)';
      for (let i = 0; i < 40 && getComputedStyle(panel).backgroundColor !== expected; i++) {
        await new Promise(resolve => setTimeout(resolve, 50));
      }
      for (let i = 0; i < 40 && Number(getComputedStyle(panel).opacity) < 0.99; i++) {
        await new Promise(resolve => setTimeout(resolve, 25));
      }
      const style = getComputedStyle(panel);
      if (style.backgroundColor !== expected) throw Error('dialog theme background incorrect: ' + style.backgroundColor);
      if (Number(style.opacity) < 0.99) throw Error('dialog did not finish its opening transition');
      const luminance = color => {
        const rgb = color.match(/\d+/g).slice(0, 3).map(value => {
          const channel = Number(value) / 255;
          return channel <= 0.04045 ? channel / 12.92 : Math.pow((channel + 0.055) / 1.055, 2.4);
        });
        return rgb[0] * 0.2126 + rgb[1] * 0.7152 + rgb[2] * 0.0722;
      };
      const background = luminance(style.backgroundColor);
      const text = luminance(getComputedStyle(panel.querySelector('#description')).color);
      const contrast = (Math.max(background, text) + 0.05) / (Math.min(background, text) + 0.05);
      if (contrast < 4.5) throw Error('dialog text contrast too low: ' + contrast);
      const close = panel.querySelector('#buttons').getBoundingClientRect();
      if (close.top < 0 || close.bottom > innerHeight) throw Error('dialog close button outside viewport');
    }).toString() + ')(' + JSON.stringify(selector) + ',' + JSON.stringify(dark) + ')');
    await page('Runtime.enable');
    await page('Network.enable');
    await page('Network.setBlockedURLs', { urls: ['https://*'] });
    await page('Page.enable');
    await page('Page.addScriptToEvaluateOnNewDocument', { source: "if (!localStorage.getItem('gameState')) localStorage.setItem('gameState', JSON.stringify({version:1.4,game:{prologue:{done:true}},playStats:{audioAlertShown:true}}));" });
    await page('Page.navigate', { url: 'http://127.0.0.1:' + server.address().port + '/index.html?lang=zh_cn' });
    let ready = false;
    for (let i = 0; i < 100; i++) {
      ready = await evaluate('!!(window.Engine && Engine.activeModule && window.CombatStyles && window.CastleReport)');
      if (ready) break;
      await pause(100);
    }
    assert.ok(ready, 'game modules did not initialize');
    // Room's initial income tick is untracked until it creates Engine._incomeTimeout.
    // Let it finish before freezing income for asynchronous inventory assertions below.
    await pause(1100);
    await evaluate(`(function() {
      $SM.set('game.fire.value',3); $SM.set('game.temperature.value',4);
      $SM.set('game.builder.level',4); $SM.set('features.location.outside',true);
      $SM.set('stores.wood',20); EarlyGame.render();
      const guide = document.querySelector('#roomPanel .earlyGameTask').getBoundingClientRect();
      const builds = document.querySelector('#buildBtns').getBoundingClientRect();
      if (builds.top < guide.bottom) throw Error('early guidance overlaps build controls');
    })()`);
    const earlyImage = await page('Page.captureScreenshot', {format:'png'});
    const earlyOutput = path.join(profile, 'early-game.png');
    fs.writeFileSync(earlyOutput, Buffer.from(earlyImage.data, 'base64'));
    console.log('SCREENSHOT: ' + earlyOutput);
    const checks = await evaluate(`(async function() {
      const checks = [];
      const check = (condition, name) => {
        if (!condition) throw Error(name + ': ' + JSON.stringify({floor: Space.currentFloor, scene: Events.activeScene, stack: Events.eventStack.map(e => ({title:e.title,ending:e.ending})), done:Space.done, module:Engine.activeModule.name, embarks:$SM.get('game.embarks'), food:$SM.get('stores["cured meat"]'), sword:$SM.get('stores["nichirin katana"]')}));
        checks.push(name);
      };
      const finishClick = async selector => {
        const before = Events.activeEvent();
        $(selector).trigger('click');
        for (let i = 0; i < 100; i++) {
          if (Events.activeEvent() !== before) return;
          await new Promise(resolve => setTimeout(resolve, 30));
        }
        throw Error('event did not finish: ' + selector);
      };
      const until = async predicate => {
        for (let i = 0; i < 160; i++) {
          if (predicate()) return;
          await new Promise(resolve => setTimeout(resolve, 30));
        }
        throw Error('browser state did not settle: ' + JSON.stringify({checks,focus:document.activeElement.tagName,key:$('#attack_nichirin-katana').attr('data-hotkey'),visible:$('#attack_nichirin-katana').is(':visible'),classes:$('#attack_nichirin-katana').attr('class'),cooldown:$('#attack_nichirin-katana').data('onCooldown'),hp:$('#enemy').data('hp')}));
      };
      AudioEngine.playSound = AudioEngine.playBackgroundMusic = AudioEngine.playEventMusic = function() {};
      Engine.options.testerMode = false;
      clearTimeout(Engine._incomeTimeout); // Keep fixture inventory stable during asynchronous confirmation fades.
      check($('#roomPanel .earlyGameTask').length === 1, 'new saves show one collapsible estate task');
      $SM.set('game.fire.value', 3); $SM.set('game.temperature.value', 4);
      $SM.set('game.builder.level', 4);
      if (!Outside.panel) Outside.init();
      $SM.set('game.builder.level',1); $SM.set('game.temperature.value',2); $SM.set('stores.wood',5);
      EarlyGame.render();
      check($('#roomPanel .guestCare').is(':visible') && $('#roomPanel .guestCare').prop('disabled'), 'guest interaction explains warmth prerequisite');
      check(!$('#roomPanel .campaignGoal').is(':visible'), 'opening rescue does not show premature construction milestones');
      $SM.set('game.temperature.value',3);
      $('#roomPanel .guestCare').trigger('click');
      check($SM.get('game.builder.level') === 2 && $SM.get('stores.wood') === 4, 'first care click advances one recovery stage and pays one wood');
      $('#roomPanel .guestCare').trigger('click');
      check($SM.get('game.builder.level') === 4 && $SM.get('stores.wood') === 3 && $SM.get('income.builder.stores.wood') === 2, 'second care click introduces Shinobu and starts real helper income');
      const caredWood=$SM.get('stores.wood');
      Room.updateBuilderState(); EarlyGame.tendGuest();
      check($SM.get('stores.wood') === caredWood && !$('#roomPanel .guestCare').is(':visible'), 'finished care hides its button and ignores pending recovery');
      $SM.set('stores.wood',30);
      EarlyGame.render();
      check($('#roomPanel .earlyGameTaskText').text().includes('推车'), 'early guidance explains the cart upgrade');
      $('#roomPanel .earlyGameTask').prop('open', false);
      $SM.add('stores.wood', 1);
      check(!$('#roomPanel .earlyGameTask').prop('open'), 'income updates preserve collapsed guidance');
      $SM.set('game.gatherCount', 0);
      $('#gatherButton').trigger('click');
      check($SM.get('cooldown.gatherButton') === 20, 'first wood gathering uses the real 20-second button cooldown');
      Button.clearCooldown($('#gatherButton'));
      $SM.set('game.gatherCount', 3);
      $('#gatherButton').trigger('click');
      check($SM.get('cooldown.gatherButton') === 60, 'normal gathering cooldown resumes after three uses');
      Button.clearCooldown($('#gatherButton'));
      $SM.set('game.buildings.trap',1);
      Outside.updateTrapButton(); // Normally refreshed when travelling back to the forest.
      const firstFur=$SM.get('stores.fur',true), firstMeat=$SM.get('stores.meat',true);
      $('#trapsButton').trigger('click');
      check($SM.get('game.firstTrapCatch') && $SM.get('stores.fur') >= firstFur+3 && $SM.get('stores.meat') >= firstMeat+2, 'actual first trap check guarantees useful opening materials');
      Button.clearCooldown($('#trapsButton'));
      $SM.set('game.buildings.lodge',1);
      $('#roomPanel .earlyGameTask').prop('open',true);
      EarlyGame.render();
      check($('#roomPanel .openingSupply button').length === 2 && $('#roomPanel .openingSupply').is(':visible'), 'earned lodge offers two explicit one-time supplies');
      const choiceFur=$SM.get('stores.fur'), choiceFood=$SM.get('stores["cured meat"]',true);
      $('#roomPanel .openingSupply button[data-choice="journey"]').trigger('click');
      check($SM.get('game.openingSupplyChoice') === 'journey' && $SM.get('stores.fur') === choiceFur+180 && $SM.get('stores["cured meat"]') === choiceFood+5, 'real supply choice grants exactly the advertised materials');
      $('#outsidePanel .openingSupply button[data-choice="estate"]').trigger('click');
      check($SM.get('stores.fur') === choiceFur+180 && !$('.openingSupply').is(':visible') && !$SM.get('features.location.path'), 'duplicate panel cannot collect another choice or unlock the map');
      $SM.set('game.population',4);
      EarlyGame.render();
      const workerStores=JSON.stringify($SM.get('stores'));
      $('#roomPanel .openingHunters button').trigger('click');
      check($SM.get('game.workers.hunter') === 2 && Outside.getNumGatherers() === 2 && $SM.get('income.hunter.stores.fur') === 1, 'introductory worker button enables actual hunter production and reserves gatherers');
      check(JSON.stringify($SM.get('stores')) === workerStores && !$('.openingHunters').is(':visible'), 'worker setup grants no resources and hides after allocation');
      $SM.set('game.workers.hunter',0);
      $SM.set('playStats.audioAlertShown', true);
      $SM.set('game.population', 4);
      $SM.set('game.workers.charcutier', 2);
      $SM.setM('stores', {wood:5,meat:0});
      $('#productionOverviewButton').trigger('click');
      check(Events.eventPanel().text().includes('原料不够整组'), 'production overview identifies whole-group material shortages');
      check(Events.eventPanel().text().includes('持续供需缺口') && Events.eventPanel().text().includes('当前生产方'), 'production overview explains sustained deficits and assigned sources');
      check(Events.eventPanel().find('.productionSummary > div').length === 3 && Events.eventPanel().find('.productionBlockedRow').length > 0, 'production overview prioritizes live shortage cards and summary counts');
      $('[data-production-fold="jobs"], [data-production-fold="job:charcutier"]').prop('open',true);
      const workerCount = $SM.get('game.workers.charcutier');
      $SM.setM('stores', {wood:100,meat:100});
      $('#refresh').trigger('click');
      check(!Events.eventPanel().text().includes('原料不够整组') && $SM.get('game.workers.charcutier') === workerCount, 'production refresh reflects new stock without reassigning workers');
      check(Events.eventPanel().text().includes('持续供需缺口'), 'restocking removes immediate shortage but not the sustained supply deficit');
      check($('[data-production-fold="jobs"]')[0].open && $('[data-production-fold="job:charcutier"]')[0].open, 'refresh preserves both recipe-list and individual-job expansion');
      $('#reserves').trigger('click');
      const reserveSnapshot=JSON.stringify($SM.get('stores'));
      $('[data-material="wood"]').val('95');
      $('[data-material="meat"]').val('-1');
      $('#saveProductionReserves').trigger('click');
      check($('#productionReserveStatus').text().includes('本次未保存') && !$SM.get('game.productionReserves'), 'invalid reserve form never partially saves');
      $('[data-material="meat"]').val('0');
      $('#saveProductionReserves').trigger('click');
      check($SM.getProductionReserve('wood') === 95 && Events.eventPanel().text().includes('为保留库存暂停'), 'saved reserves explain why an affordable batch is held');
      check($('[data-production-fold="jobs"]')[0].open && $('[data-production-fold="job:charcutier"]')[0].open, 'returning from reserve settings keeps recipe sections expanded');
      check(JSON.stringify($SM.get('stores')) === reserveSnapshot, 'saving reserves never consumes inventory');
      $('#reserves').trigger('click');
      $('[data-material="wood"]').val('0');
      $('#cancelProductionReserves').trigger('click');
      check($SM.getProductionReserve('wood') === 95, 'cancel leaves reserve settings untouched');
      $('#reserves').trigger('click');
      $('[data-material="wood"]').val('0');
      $('#saveProductionReserves').trigger('click');
      check($SM.getProductionReserve('wood') === 0 && !Events.eventPanel().text().includes('为保留库存暂停'), 'zero disables reserve protection');
      await finishClick('#close');
      $SM.set('game.workers.charcutier', 0);
      $SM.setM('stores', {'wind armour':1,'nichirin katana':1,'bind kunai':1,'medicine':30,'cured meat':30,'wisteria oil':20,'teeth':100,'scales':100,'wood':100,'demon stone':5});
      if (!Path.panel) Path.init();
      check(EarlyGame.task() === null && $('.campaignClaim').length > 0, 'world exploration replaces opening guidance with continuing campaign milestones');
      const beforeCampaignWood=$SM.get('stores.wood');
      $('#roomPanel .campaignClaim').trigger('click');
      check($SM.get('game.campaignClaims.cart') && $SM.get('stores.wood') === beforeCampaignWood+40, 'campaign claim grants the advertised reward');
      const afterCampaignWood=$SM.get('stores.wood');
      EarlyGame.claimMilestone('cart');
      check($SM.get('stores.wood') === afterCampaignWood, 'duplicate campaign claims never repeat rewards');
      if (!World.panel) World.init();
      Engine.activeModule=Path;
      $SM.set('character.equippedInit',true,true);
      $SM.set('character.equipped',{primary:['nichirin katana'],secondary:[],tool:[]});
      Path.outfit={}; $SM.set('outfit',{});
      Path.updateOutfitting();
      check($('#journeyGuide .journeyChecklist').text().includes('口粮待备'), 'new explorers see live actual backpack checks');
      const beginnerStock=JSON.stringify($SM.get('stores'));
      $('#prepareJourneyBtn').trigger('click');
      check(Path.outfit['nichirin katana'] === 1 && Path.outfit['cured meat'] === 5 && $('#journeyGuide .journeyChecklist').text().includes('口粮已备'), 'beginner preparation button packs selected weapon and five food within starter capacity');
      check(JSON.stringify($SM.get('stores')) === beginnerStock && $SM.get('character.loadouts.expedition.targets["cured meat"]') === 5, 'beginner setup saves reusable targets without charging warehouse');
      $('#journeyGuide').prop('open',false);
      $SM.add('stores.wood',1);
      check(!$('#journeyGuide').prop('open'), 'live preparation checks preserve collapsed state');
      $SM.set('game.embarks',3);
      Path.updateJourneyGuide();
      check(!$('#journeyGuide').is(':visible'), 'beginner preparation guide retires after three departures');
      $SM.set('game.embarks',0);
      if (!Ship.panel) Ship.init();
      $SM.setM('stores', {'wisteria gun':1,'wisteria bomb':1});
      $SM.set('character.equipped.secondary',['wisteria gun','wisteria bomb']);
      Path.updateEquipDoll();
      const gearBefore = JSON.stringify($SM.get('character.equipped'));
      Path.showEquipPicker($('.equipSlot[data-cat="secondary"][data-slot="1"]'), 'secondary', 1);
      const comparison = $('.pickerOption[data-weapon="wisteria gun"] .weaponCompareDetails').text();
      check(comparison.includes('基础伤害：15 → 5') && comparison.includes('没有足够弹药'), 'equipment picker compares base values and warns about missing ammunition');
      check(JSON.stringify($SM.get('character.equipped')) === gearBefore, 'viewing weapon comparisons never changes equipment');
      $('.pickerOption[data-weapon="wisteria gun"]').trigger('click');
      check(Path.getEquippedSlots('secondary')[0] === null && Path.getEquippedSlots('secondary')[1] === 'wisteria gun', 'selecting a compared weapon preserves slot deduplication');
      $SM.set('character.equipped.secondary', [null,null]);
      Path.setEquipSlot('primary', 0, 'nichirin katana');
      Engine.activeModule = Path;
      Path.outfit = {'nichirin katana':1,'cured meat':5};
      const homeFood = $SM.get('stores["cured meat"]');
      Path.checkEmbark();
      check(Events.eventPanel().text().includes('第一次出门'), 'first expedition explains food, water and real-time combat');
      $SM.set('stores["cured meat"]', 4, true);
      await finishClick('#depart');
      check(Engine.activeModule === Path && !$SM.get('game.embarks', true) && $SM.get('stores["nichirin katana"]') === 1, 'stale expedition confirmation never partially charges stock');
      $SM.set('stores["cured meat"]', homeFood, true);
      Path.checkEmbark();
      await finishClick('#depart');
      check(Engine.activeModule === World && $SM.get('game.embarks') === 1 && $SM.get('stores["cured meat"]') === homeFood - 5, 'first expedition enters the actual world and charges once');
      check(Path.embark() === false, 'duplicate expedition departure is ignored');
      World.goHome();
      check(Engine.activeModule === Path && $SM.get('stores["cured meat"]') === homeFood, 'returning home restores unused expedition supplies');
      check(ExpeditionReport.latest().steps === 0 && !$SM.get('previous.embarkSnapshot'), 'zero-net trip produces a completed report and clears departure snapshot');
      const zeroTripStock=JSON.stringify($SM.get('stores'));
      check(World.goHome() === false && JSON.stringify($SM.get('stores')) === zeroTripStock, 'duplicate world return cannot credit inventory twice');
      $SM.set('stores.rucksack',1); // Treatment supplies need space beyond the first starter outfit.
      Path.outfit={'nichirin katana':1,'cured meat':5,medicine:2}; $SM.set('outfit',Path.outfit);
      const tripFood=$SM.get('stores["cured meat"]');
      check(Path.embark(), 'fresh world expedition begins new in-memory accounting');
      await new Promise(resolve=>$('#outerSlider').promise().done(resolve));
      check($('#worldFieldTreatment').is(':visible') && $('#worldHeal_medicine').prop('disabled'), 'map treatment appears but full health does not consume medicine');
      World.setHp(World.getMaxHealth()-3);
      check(FieldTreatment.info('medicine').heal === 3, 'map treatment previews clamped actual healing');
      const fieldStock=JSON.stringify($SM.get('stores'));
      const fieldCounters=[World.foodMove,World.waterMove,World.water];
      document.body.focus();
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'2',bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'2',repeat:true,bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup',{key:'2',bubbles:true}));
      check(World.health === World.getMaxHealth() && Path.outfit.medicine === 1, 'map medicine hotkey consumes one item and restores actual health without held-key repeats');
      check(JSON.stringify($SM.get('stores')) === fieldStock && JSON.stringify(fieldCounters) === JSON.stringify([World.foodMove,World.waterMove,World.water]), 'field treatment touches neither home stock nor travel consumption counters');
      World.setHp(World.getMaxHealth()-3);
      $('#worldHeal_medicine').trigger('click');
      check(Path.outfit.medicine === 1 && World.health === World.getMaxHealth()-3, 'map treatment cooldown prevents repeated consumption');
      Events.startEvent({title:'field treatment isolation',scenes:{start:{text:['test'],buttons:{fieldReturn:{text:'return',nextScene:'end'}}}}});
      check($('#worldHeal_meat').prop('disabled') && FieldTreatment.use('cured meat') === 0 && Path.outfit['cured meat'] === 5, 'active events block background field treatment');
      await finishClick('#fieldReturn');
      check(!$('#worldHeal_meat').prop('disabled'), 'field treatment becomes available again after event closes');
      World.setHp(World.getMaxHealth());
      const originalCheckFight=World.checkFight;
      World.checkFight=function() {};
      for(let x=31;x<=33;x++) World.state.map[x][30]=World.TILE.FOREST;
      for(let i=0;i<3;i++) check(World.move(World.EAST),'actual outward map step '+i);
      check(World.travelInfo().distance === 3 && World.travelInfo().budget.food === 1 && World.travelInfo().budget.water === 2, 'return reminder includes phase counters and free final home step');
      $('#worldTravelGuide').prop('open',false);
      const tripWater=World.water;
      World.setWater(1);
      check($('#worldTravelGuide').attr('data-status') === 'danger' && !$('#worldTravelGuide').prop('open'), 'low-water warning updates without reopening collapsed reminder');
      World.setWater(tripWater);
      for(let i=0;i<3;i++) check(World.move(World.WEST),'actual homeward map step '+i);
      World.checkFight=originalCheckFight;
      let expedition=ExpeditionReport.latest();
      check(Engine.activeModule === Path && expedition.steps === 6 && expedition.farthestDistance === 3 && expedition.mapSaved && expedition.newTiles > 0, 'actual return stores completed exploration progress only');
      check(expedition.reduced['cured meat'] === 2 && expedition.returned['cured meat'] === 3 && $SM.get('stores["cured meat"]') === tripFood-2, 'report matches actual net food use and remaining warehouse credit');
      check(expedition.reduced.medicine === 1 && expedition.returned.medicine === 1 && !$('#worldFieldTreatment').is(':visible'), 'field medicine appears in the actual expedition report and its controls retire on return');
      const reportSnapshot=JSON.stringify($SM.get('game.lastExpeditionReport'));
      $('#expeditionReportButton').trigger('click');
      check(Events.eventPanel().hasClass('expeditionReport') && Events.eventPanel().text().includes('不含庄园生产'), 'report entry opens read-only exploration feedback');
      await finishClick('#closeExpeditionReport');
      check(JSON.stringify($SM.get('game.lastExpeditionReport')) === reportSnapshot, 'reading completed report changes neither report nor run state');
      Path.outfit={'nichirin katana':1,'cured meat':5}; $SM.set('outfit',Path.outfit);
      const beforeDeadFur=$SM.get('stores.fur',true);
      check(Path.embark(), 'next expedition starts independently of the finished report');
      World.state.map[31][30]=World.TILE.FOREST;
      World.checkFight=function() {};
      World.move(World.EAST);
      World.checkFight=originalCheckFight;
      Path.outfit.fur=2; Path.outfit['cured meat']=0;
      World.starvation=true; World.foodMove=1;
      check(World.useSupplies() === false, 'actual starvation branch ends the world expedition');
      check(World.move(World.EAST) === false, 'death animation blocks late world movement');
      await until(()=>Engine.activeModule === Room && Engine.tabNavigation && !Engine.keyLock);
      expedition=ExpeditionReport.latest();
      check(expedition.outcome === 'death' && expedition.reason === 'food' && !expedition.mapSaved && expedition.returned['nichirin katana'] === 1 && expedition.gained.fur === 2, 'failure report identifies real starvation without falsely losing returned weapons or loot');
      check($SM.get('stores.fur') === beforeDeadFur+2 && $SM.get('stores["nichirin katana"]') === 1 && ExpeditionReport._run === null, 'death actually returns remaining loot and leaves no resumable report state');
      Engine.travelTo(Path);
      await new Promise(resolve=>$('#locationSlider').promise().done(resolve));
      $SM.set('stores.rucksack', 1); // Later loadout/style cases carry more than the starter bag allows.
      Path.outfit = { medicine:3, 'cured meat':2 };
      $SM.set('outfit', Path.outfit);
      $('#loadoutSelect').val('castle').trigger('change');
      $('#saveLoadoutBtn').trigger('click');
      check($SM.get('character.loadouts.castle').targets.medicine === 3, 'save loadout button records targets');
      Path.outfit.medicine = 1;
      const storedMedicine = $SM.get('stores.medicine');
      $('#loadoutPreview').prop('open', true);
      Path.updateOutfitting();
      const previewSnapshot = JSON.stringify({bag:Path.outfit, stores:$SM.get('stores'), equipment:$SM.get('character.equipped')});
      Path.updateLoadoutPanel();
      check($('#loadoutPreview').text().includes('已装 1／目标 3；补齐后预计 3'), 'loadout preview shows packed, target and planned quantities');
      check(JSON.stringify({bag:Path.outfit, stores:$SM.get('stores'), equipment:$SM.get('character.equipped')}) === previewSnapshot, 'loadout preview never mutates inventory or equipment');
      $SM.set('stores.medicine', 2);
      check($('#loadoutPreview').text().includes('库存缺 1') && $('#loadoutPreview').prop('open'), 'stock changes refresh shortages without collapsing the preview');
      $SM.set('stores.medicine', storedMedicine);
      $('#autoFillBtn').trigger('click');
      check(Path.outfit.medicine === 3 && $SM.get('stores.medicine') === storedMedicine, 'refill button tops up without charging inventory twice');
      check($('#loadoutPreview').text().includes('已装 3／目标 3；补齐后预计 3'), 'refill updates the live preview');
      Engine.activeModule = Ship;
      $SM.addPerk('water breath I'); $SM.addPerk('flame breath I'); $SM.addPerk('thunder breath I');
      Ship.onArrival();
      $('[data-style="water"]').trigger('click');
      check(CombatStyles.getSelected() === 'water', 'form picker selects an unlocked style');
      check(!!document.querySelector('#shipPanel'), 'castle entrance renders');
      check(_('view last castle report') === '查看上次无限城战报', 'new and old translations coexist');
      check(_('medicine') !== 'medicine', 'original translations preserved');
      Path.outfit = {'nichirin katana':1,'medicine':5,'cured meat':5,'wisteria oil':5};
      $SM.set('outfit', Path.outfit);
      $SM.set('game.spaceShip.crows', 2);
      Ship.checkDescend();
      check(Events.eventPanel().text().includes('本次流派：'), 'departure summary translations are loaded');
      const departureMedicine = $SM.get('stores.medicine');
      $SM.set('stores.medicine', 4);
      await finishClick('#descend');
      check(Engine.activeModule === Ship && $SM.get('game.spaceShip.crows') === 2 && $SM.get('stores.medicine') === 4, 'stale departure is rejected without partial charges');
      $SM.set('stores.medicine', departureMedicine);
      Ship.checkDescend();
      await finishClick('#descend');
      check(Engine.activeModule === Space && $SM.get('game.spaceShip.crows') === 1 && $SM.get('stores.medicine') === departureMedicine - 5, 'confirmed departure charges inventory and one crow exactly once');
      check(World.health === World.getMaxHealth(), 'entry applies inherited HP before healing');
      World.setHp(World.health - 20);
      Space.showFloor();
      const beforeHeal = World.health;
      const medCount = Path.outfit.medicine;
      $('#spacePanel [data-hotkey="2"]').trigger('click');
      check(World.health > beforeHeal && Path.outfit.medicine === medCount - 1, 'preparation medicine uses real shared healing');
      const fight = () => {
        Space.triggerBattle(false);
        clearInterval(Events._enemyAttackTimer);
        (Events._specialTimers || []).forEach(clearInterval);
        $('#enemy').data('hp',1000).data('maxHp',1000);
      };
      const endFight = async () => {
        Events.clearTimeouts();
        await new Promise(resolve => Events.endEvent(resolve));
      };
      const selectForm = id => {
        Engine.activeModule = Ship;
        Ship.onArrival();
        $('[data-style="' + id + '"]').trigger('click');
        Engine.activeModule = Space;
      };
      fight();
      World.setHp(World.getMaxHealth() - 30);
      $('#wanderer').data('hp',World.health);
      const waterHealing = CastleReport._run.healingReceived;
      for(let i=0;i<3;i++) Events.damage($('#wanderer'),$('#enemy'),10,'melee',null,{weaponName:'nichirin katana'});
      check(CombatStyles._fight.combo === 0 && CombatStyles._fight.guardUntil > Date.now(), 'actual water hits activate flow guard');
      check(CastleReport._run.healingReceived > waterHealing + 3, 'water healing is included in the report');
      const attackButton = $('#attack_nichirin-katana');
      check(attackButton.length === 1, 'equipped melee attack has a real button');
      const key = attackButton.attr('data-hotkey');
      Space.setTalentLevel('steadyHand',20);
      const enemyHp = $('#enemy').data('hp');
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup',{key,bubbles:true}));
      await until(() => $('#enemy').data('hp') < enemyHp);
      check(!Engine._hotkeyDown[key], 'native keyup releases combat shortcut');
      const combatMedicine = Path.outfit.medicine;
      const combatHp = World.health;
      const healKey = $('#meds').attr('data-hotkey');
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:healKey,bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup',{key:healKey,bubbles:true}));
      check(Path.outfit.medicine === combatMedicine - 1 && World.health > combatHp, 'native medicine shortcut heals and consumes exactly once');
      await endFight();
      selectForm('flame'); fight();
      Events.damage($('#wanderer'),$('#enemy'),10,'melee',null,{weaponName:'nichirin katana'});
      const cutHp = $('#enemy').data('hp');
      await until(() => $('#enemy').data('hp') < cutHp);
      check(!!CombatStyles._fight.wound, 'flame cut deals timed damage through the combat engine');
      await endFight();
      check(CombatStyles._woundTimer === null, 'leaving combat cancels cut timers');
      selectForm('thunder'); fight();
      Events.damage($('#wanderer'),$('#enemy'),10,'melee',null,{weaponName:'nichirin katana'});
      check($('#enemy').data('hp') === 984, 'charged thunder hit deals 60% extra damage');
      Events.damage($('#wanderer'),$('#enemy'),10,'melee',null,{weaponName:'nichirin katana'});
      check($('#enemy').data('hp') === 974, 'immediate thunder follow-up spends no second charge');
      await endFight();
      selectForm('technique'); fight();
      Events.damage($('#wanderer'),$('#enemy'),'stun','ranged',null,{weaponName:'bind kunai'});
      Events.damage($('#wanderer'),$('#enemy'),10,'melee',null,{weaponName:'nichirin katana'});
      check($('#enemy').data('hp') === 986, 'control hit opens the technique damage window');
      const warningScene = Events.activeEvent().scenes[Events.activeScene];
      warningScene.telegraphAttacks = [Space.BLOOD_ARTS.charged(5)];
      CombatTelegraphs.start(warningScene, $('#description'));
      $('#enemy').data('stunned', false);
      const beforeWarningTop = document.querySelector('#attackButtons').getBoundingClientRect().top;
      CombatTelegraphs.queue(warningScene.telegraphAttacks[0]);
      const charge = CombatTelegraphs._fight.charges[0];
      check($('.combatTelegraph').length === 1 && $('.combatTelegraphCountdown').text().includes('秒后出招'), 'blood-art countdown renders beside combat controls');
      check(Math.abs(document.querySelector('#attackButtons').getBoundingClientRect().top - beforeWarningTop) < 1, 'warnings do not shift attack buttons');
      check(document.querySelector('#fight').getBoundingClientRect().bottom <= document.querySelector('.combatTelegraphs').getBoundingClientRect().top, 'fighter health and warnings never overlap');
      Events.damage($('#wanderer'),$('#enemy'),'stun','ranged',null,{weaponName:'bind kunai'});
      check(CombatTelegraphs._fight.charges.length === 0 && !$('#enemy').hasClass('charging'), 'actual control hit cancels the pending blood art');
      $('#enemy').data('stunned', false);
      const beforeCancelled = World.health;
      CombatTelegraphs._resolve(charge, CombatTelegraphs._fight);
      check(World.health === beforeCancelled, 'cancelled cast stays cancelled after stun ends');
      const bleed = {telegraphSec:1,dmg:10,hit:1,bleedSec:3,bleedPerSec:2};
      const intervalCount = CombatTelegraphs._fight.intervals.length;
      $('#wanderer').data('status','shield');
      CombatTelegraphs.queue(bleed);
      CombatTelegraphs._resolve(CombatTelegraphs._fight.charges[0], CombatTelegraphs._fight);
      await until(() => $('#wanderer').data('status') !== 'shield');
      check(CombatTelegraphs._fight.intervals.length === intervalCount, 'shield absorption does not start bleeding');
      const damageBefore = CastleReport._run.damageTaken;
      CombatTelegraphs.queue(bleed);
      CombatTelegraphs._resolve(CombatTelegraphs._fight.charges[0], CombatTelegraphs._fight);
      await until(() => CastleReport._run.damageTaken > damageBefore);
      check(CombatTelegraphs._fight.intervals.length === intervalCount + 1, 'a damaging blood-art hit starts bleeding');
      await endFight();
      fight();
      Path.outfit.medicine = 1;
      const homeBeforePickup = $SM.get('stores.medicine');
      const gearBeforePickup = JSON.stringify($SM.get('character.equipped'));
      Space.collectConfiguredLoot();
      check(Path.outfit.medicine === 1, 'configured pickup cannot run during combat');
      Events.clearTimeouts();
      Events.won = true;
      Events.fought = true;
      $('#description').empty(); $('#buttons').empty();
      Events.drawLoot({medicine:{min:4,max:4,chance:1},scales:{min:5,max:5,chance:1}});
      $('<div id="exitButtons">').appendTo('#buttons');
      Events.drawButtons(Events.activeEvent().scenes.start);
      const homeScalesBeforePickup=$SM.get('stores.scales');
      Button.clearCooldown($('#collectConfigured'));
      await finishClick('#collectConfigured');
      check(Path.outfit.medicine === 3 && $SM.get('stores.medicine') === homeBeforePickup + 2, 'one-click pickup fills saved medicine target and banks only the remainder');
      check($SM.get('stores.scales') === homeScalesBeforePickup + 5 && JSON.stringify($SM.get('character.equipped')) === gearBeforePickup, 'one-click pickup banks materials without changing equipment');
      check(Events.activeEvent().title === _('slayer talent'), 'one-click collection still requires a manual talent choice');
      check(Events.eventPanel().text().includes('下次入城继承') && Events.eventPanel().text().includes('→'), 'talent choices show numerical and inheritance previews');
      const afterPickupStock=$SM.get('stores.medicine');
      Space.collectConfiguredLoot();
      check($SM.get('stores.medicine') === afterPickupStock, 'a late pickup callback cannot duplicate rewards');
      await finishClick('#talent_0');
      Space.currentFloor = 10;
      Space.triggerBossFight();
      Events.clearTimeouts();
      Events.won = true;
      Events.fought = true;
      $('#buttons').empty();
      Events.drawLoot(Events.activeEvent().scenes.start.loot);
      const earnedScales = $('#lootButtons .lootRow').filter(function() {return $(this).data('item') === 'scales';}).find('.lootTake').data('numLeft');
      check(earnedScales >= 20 && earnedScales <= 30, 'real boss loot renders guaranteed scales');
      const scalesBeforeLoot = $SM.get('stores.scales', true);
      $SM.set('stores.convoy',1);
      const packedScalesBefore = Path.outfit.scales || 0;
      Events.getLoot($('#lootButtons .lootRow').filter(function() {return $(this).data('item') === 'scales';}).find('.lootTake'));
      check(Path.outfit.scales === packedScalesBefore + 1 && $SM.get('stores.scales') === scalesBeforeLoot, 'manual loot is packed without a duplicate warehouse credit');
      Space._collectRemainingLoot();
      Space._collectRemainingLoot();
      check($SM.get('stores.scales') === scalesBeforeLoot + earnedScales - 1, 'support corps transfers scales to warehouse exactly once');
      $('<div id="exitButtons">').appendTo('#buttons');
      Events.drawButtons(Events.activeEvent().scenes.start);
      $('#recraft').trigger('click');
      check(Events.activeScene === 'recraft' && $('#recraft_0').length === 1, 'boss supply scene visible');
      const beforePurchase = Path.outfit.medicine;
      const scalesBeforePurchase = $SM.get('stores.scales');
      $('#recraft_0').trigger('click'); $('#recraft_0').trigger('click');
      check(Path.outfit.medicine === beforePurchase + 2, 'repeat purchases stay in supply scene');
      check($SM.get('stores.scales') === scalesBeforePurchase - 16, 'boss medicine purchases consume warehouse scales at the displayed recipe');
      await finishClick('#leave');
      check(Events.activeEvent().title === _('slayer talent'), 'first boss reward opens after supply closes');
      await finishClick('#talent_0');
      check(Events.activeEvent().title === _('slayer talent'), 'second boss reward opens');
      await finishClick('#talent_0');
      check(Space.currentFloor === 11 && !Events.activeEvent(), 'boss rewards advance once');
      fight();
      const deathScene = Events.activeEvent().scenes[Events.activeScene];
      deathScene.telegraphAttacks = [{telegraphSec:1,dmg:999,hit:1}];
      CombatTelegraphs.start(deathScene, $('#description'));
      $SM.addPerk('total concentration');
      const beforeRecovery = CastleReport._run.healingReceived;
      CombatTelegraphs.queue(deathScene.telegraphAttacks[0]);
      CombatTelegraphs._resolve(CombatTelegraphs._fight.charges[0], CombatTelegraphs._fight);
      await until(() => Events._deathRecoveryUsed);
      check(World.health > 0 && CastleReport._run.healingReceived > beforeRecovery, 'fatal blood art triggers second wind and records actual recovery');
      CombatTelegraphs.queue(deathScene.telegraphAttacks[0]);
      CombatTelegraphs._resolve(CombatTelegraphs._fight.charges[0], CombatTelegraphs._fight);
      await until(() => !!document.querySelector('#castleReportOverlay'));
      const report = CastleReport.getLastReport();
      check(!!report && !!$SM.get('game.castleLastReport'), 'read-only result saved');
      check(Engine.activeModule === Room && World.dead && !Events.activeEvent(), 'real death returns to camp before showing the report');
      check(document.querySelector('[role="dialog"]') !== null, 'result dialog renders');
      check(document.querySelector('[role="dialog"]').textContent.includes('本次材料账本') && report.materials.find(row=>row.item==='scales').spent === 16, 'completed report displays actual material spending');
      check(document.querySelector('.castle-report-stats dd').textContent === String(report.highestFloor), 'report displays the numeric floor');
      check(CastleReport._run === null && !('floorNodes' in report), 'finished report cannot resume a descent');
      const savedFood = $SM.get('stores["cured meat"]');
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'1',bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup',{key:'1',bubbles:true}));
      check($SM.get('stores["cured meat"]') === savedFood, 'report shortcuts do not consume background supplies');
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
      check(!document.querySelector('#castleReportOverlay') && !Engine.keyLock, 'Escape closes report and restores controls');
      CastleReport.show();
      return checks;
    })()`);
    console.log(checks.map(name => 'PASS: ' + name).join('\n'));
    const screenshot = await page('Page.captureScreenshot', { format: 'png', captureBeyondViewport: false });
    const output = path.join(profile, 'castle-report.png');
    fs.writeFileSync(output, Buffer.from(screenshot.data, 'base64'));
    console.log('SCREENSHOT: ' + output);
    await evaluate(`(async function() {
      CastleReport.close();
      Engine.activeModule = Ship;
      Ship.onArrival();
      $SM.setM('stores', {'nichirin katana':1,'wisteria gun':1,medicine:5});
      $SM.set('game.spaceShip.crows', 1);
      $SM.set('character.equipped.primary', ['nichirin katana']);
      $SM.set('character.equipped.secondary', ['wisteria gun']);
      Path.outfit = {'nichirin katana':1,'wisteria gun':1,medicine:5};
      Ship.checkDescend();
      await new Promise(resolve => setTimeout(resolve, 250));
    })()`);
    const departureImage = await page('Page.captureScreenshot', {format:'png'});
    const departureOutput = path.join(profile, 'departure-check.png');
    fs.writeFileSync(departureOutput, Buffer.from(departureImage.data, 'base64'));
    console.log('SCREENSHOT: ' + departureOutput);
    await evaluate(`(async function() {
      await new Promise(resolve => Events.endEvent(resolve));
      Ship.descend();
      Space.currentFloor = 10;
      Space.triggerBossFight();
      clearInterval(Events._enemyAttackTimer);
      (Events._specialTimers || []).forEach(clearInterval);
      const attack = Space.BLOOD_ARTS.charged(12);
      CombatTelegraphs.queue(attack);
      await new Promise(resolve => setTimeout(resolve, 250));
      const buttons = document.querySelector('#attackButtons').getBoundingClientRect();
      if (buttons.bottom > window.innerHeight) throw Error('warning pushes combat controls below viewport');
    })()`);
    const warningImage = await page('Page.captureScreenshot', {format:'png'});
    const warningOutput = path.join(profile, 'combat-warning.png');
    fs.writeFileSync(warningOutput, Buffer.from(warningImage.data, 'base64'));
    console.log('SCREENSHOT: ' + warningOutput);
    await evaluate(`(async function() {
      Events.clearTimeouts();
      await new Promise(resolve => Events.endEvent(resolve));
      Engine.activeModule = Outside;
      Outside.onArrival();
      $SM.set('game.workers.charcutier', 2);
      $SM.setM('stores', {wood:5,meat:0});
      CampGuide.showProduction();
      await new Promise(resolve => setTimeout(resolve, 250));
      const close = document.querySelector('#close').getBoundingClientRect();
      if (close.bottom > window.innerHeight) throw Error('production report hides its close button');
    })()`);
    const productionImage = await page('Page.captureScreenshot', {format:'png'});
    const productionOutput = path.join(profile, 'production-overview.png');
    fs.writeFileSync(productionOutput, Buffer.from(productionImage.data, 'base64'));
    console.log('SCREENSHOT: ' + productionOutput);
    await evaluate(`(async function() {
      $('#reserves').trigger('click');
      await new Promise(resolve => setTimeout(resolve, 350));
      const save = document.querySelector('#saveProductionReserves').getBoundingClientRect();
      if (save.bottom > innerHeight || save.top < 0) throw Error('production reserve save button outside viewport');
    })()`);
    const reserveImage = await page('Page.captureScreenshot', {format:'png'});
    const reserveOutput = path.join(profile, 'production-reserves.png');
    fs.writeFileSync(reserveOutput, Buffer.from(reserveImage.data, 'base64'));
    console.log('SCREENSHOT: ' + reserveOutput);
    await evaluate(`(async function() {
      await new Promise(resolve => Events.endEvent(resolve));
      Space.done = true;
      Space.returnToShip();
      await new Promise(resolve => $('#outerSlider').promise().done(resolve));
      CastleReport.close();
      Engine.travelTo(Path);
      await new Promise(resolve => $('#locationSlider').promise().done(resolve));
      $SM.set('character.equipped.secondary', ['wisteria bomb','wisteria gun']);
      $SM.setM('stores', {'wisteria gun':1,'wisteria bomb':1});
      Path.updateEquipDoll();
      Path.showEquipPicker($('.equipSlot[data-cat="secondary"][data-slot="0"]'), 'secondary', 0);
      await new Promise(resolve => setTimeout(resolve, 250));
      const picker = document.querySelector('.equipPicker').getBoundingClientRect();
      if (picker.right > innerWidth || picker.bottom > innerHeight) throw Error('weapon comparison overflows the viewport');
    })()`);
    const equipmentImage = await page('Page.captureScreenshot', {format:'png'});
    const equipmentOutput = path.join(profile, 'weapon-comparison.png');
    fs.writeFileSync(equipmentOutput, Buffer.from(equipmentImage.data, 'base64'));
    console.log('SCREENSHOT: ' + equipmentOutput);
    await evaluate(`(async function() {
      $('.equipPicker').remove();
      $('#loadoutPreview').prop('open', true);
      if (!document.querySelector('#materialSourcesButton')) throw Error('material sources entry missing');
      document.querySelector('#loadoutPanel').scrollIntoView({block:'center'});
      await new Promise(resolve => setTimeout(resolve, 250));
    })()`);
    const loadoutImage = await page('Page.captureScreenshot', {format:'png'});
    const loadoutOutput = path.join(profile, 'loadout-preview.png');
    fs.writeFileSync(loadoutOutput, Buffer.from(loadoutImage.data, 'base64'));
    console.log('SCREENSHOT: ' + loadoutOutput);
    await evaluate(`(async function() {
      CampGuide.discoverEnemy('water demon');
      window.materialInventoryBefore = JSON.stringify({stores:$SM.get('stores'),outfit:Path.outfit,equipped:$SM.get('game.equipped')});
      CampGuide.showMaterialSources();
      await new Promise(resolve => setTimeout(resolve, 250));
      if (!Events.eventPanel().text().includes('距庄园 11～20 格的森林')) throw Error('discovered source location missing');
      if (Events.eventPanel().text().includes('距庄园超过 20 格的森林')) throw Error('unseen thunder demon leaked');
      if (!CampGuide.routeMaterials('battle', 1).includes('必掉')) throw Error('known material route reward missing');
      const panel=Events.eventPanel()[0];
      const source=panel.querySelector('.materialSourceYield');
      if (Number(getComputedStyle(source).fontWeight)<700) throw Error('material yields are not bold');
      if (panel.querySelector('.materialSourceRules').open) throw Error('long material explanation should start collapsed');
      const event=Events.activeEvent();
      panel.querySelector('button[data-material="teeth"]').click();
      if (panel.querySelector('button[data-material="teeth"]').getAttribute('aria-pressed')!=='true' || panel.querySelector('h2').textContent!==_('teeth')) throw Error('material selection failed');
      if (Events.activeEvent()!==event || panel.querySelectorAll('h2').length!==1) throw Error('material selection should reuse one focused panel');
      panel.querySelector('button[data-material="scales"]').click();
      if (JSON.stringify({stores:$SM.get('stores'),outfit:Path.outfit,equipped:$SM.get('game.equipped')})!==window.materialInventoryBefore) throw Error('material lookup mutated inventory');
    })()`);
    await checkDialogTheme('.materialSources', false);
    const sourceImage = await page('Page.captureScreenshot', {format:'png'});
    const sourceOutput = path.join(profile, 'material-sources.png');
    fs.writeFileSync(sourceOutput, Buffer.from(sourceImage.data, 'base64'));
    console.log('SCREENSHOT: ' + sourceOutput);
    await checkDialogTheme('.materialSources', true);
    const darkSourceImage = await page('Page.captureScreenshot', {format:'png'});
    const darkSourceOutput = path.join(profile, 'material-sources-dark.png');
    fs.writeFileSync(darkSourceOutput, Buffer.from(darkSourceImage.data, 'base64'));
    console.log('SCREENSHOT: ' + darkSourceOutput);
    await evaluate(`document.querySelector('.materialSourceRules').open=true`);
    await checkDialogTheme('.materialSources', true);
    await page('Emulation.setDeviceMetricsOverride', {width:1137,height:745,deviceScaleFactor:1,mobile:false});
    await checkDialogTheme('.materialSources', true);
    await page('Emulation.clearDeviceMetricsOverride');
    await checkDialogTheme('.materialSources', false);
    await evaluate(`(async function() {
      await new Promise(resolve => Events.endEvent(resolve));
      Engine.activeModule = Space;
      Space.done = false;
      Space.currentFloor = 1;
      Space.triggerBattle(false);
      Events.clearTimeouts();
      Events.won = true;
      Events.fought = true;
      const scene = Events.activeEvent().scenes.start;
      $('#description').empty(); $('#buttons').empty();
      Events.startStory(Object.assign({}, scene, {text:[scene.deathMessage]}));
      await new Promise(resolve => setTimeout(resolve, 350));
      const button = document.querySelector('#collectConfigured').getBoundingClientRect();
      if (button.bottom > innerHeight || button.top < 0) throw Error('configured pickup button outside viewport');
    })()`);
    const pickupImage = await page('Page.captureScreenshot', {format:'png'});
    const pickupOutput = path.join(profile, 'configured-pickup.png');
    fs.writeFileSync(pickupOutput, Buffer.from(pickupImage.data, 'base64'));
    console.log('SCREENSHOT: ' + pickupOutput);
    await evaluate(`(async function() {
      await new Promise(resolve => Events.endEvent(resolve));
      Space._offerTalent();
      await new Promise(resolve => setTimeout(resolve, 350));
      const choice = document.querySelector('#talent_0').getBoundingClientRect();
      const skip = document.querySelector('#skip').getBoundingClientRect();
      if (choice.top < 0 || skip.bottom > innerHeight) throw Error('talent preview hides choices');
    })()`);
    const talentImage = await page('Page.captureScreenshot', {format:'png'});
    const talentOutput = path.join(profile, 'talent-preview.png');
    fs.writeFileSync(talentOutput, Buffer.from(talentImage.data, 'base64'));
    console.log('SCREENSHOT: ' + talentOutput);
    await evaluate(`(async function() {
      await new Promise(resolve => Events.endEvent(resolve));
      Engine.travelTo(Room);
      await new Promise(resolve => $('#locationSlider').promise().done(resolve));
      window.scrollTo(0,0);
      $SM.set('features.location.path',false);
      $SM.set('stores.compass',0);
      $SM.set('game.builder.level',1); $SM.set('game.temperature.value',3); $SM.set('stores.wood',5);
      $('#roomPanel .earlyGameTask').prop('open',true);
      EarlyGame.render();
      $('#content, #main, #locationSlider, #roomPanel').scrollTop(0);
      window.scrollTo(0,0);
      if (!$('#roomPanel .guestCare').is(':visible') || $('#roomPanel .guestCare').prop('disabled')) throw Error('care entry inaccessible');
    })()`);
    const careImage = await page('Page.captureScreenshot', {format:'png'});
    const careOutput = path.join(profile, 'opening-care.png');
    fs.writeFileSync(careOutput, Buffer.from(careImage.data, 'base64'));
    console.log('SCREENSHOT: ' + careOutput);
    await evaluate(`(function() {
      $SM.set('game.builder.level',4); $SM.set('game.buildings.lodge',1);
      $SM.set('game.openingSupplyChoice',false);
      $SM.set('game.campaignClaims',{cart:true,shelter:true,traps:true,hunters:true});
      EarlyGame.render();
      $('#content, #main, #locationSlider, #roomPanel').scrollTop(0);
      window.scrollTo(0,0);
      const guide=document.querySelector('#roomPanel .earlyGameTask').getBoundingClientRect();
      const builds=document.querySelector('#buildBtns').getBoundingClientRect();
      const choice=document.querySelector('#roomPanel .openingSupply button[data-choice="estate"]').getBoundingClientRect();
      if (guide.top < 0 || builds.top < guide.bottom || choice.bottom > innerHeight) throw Error('opening choices overlap building controls or leave viewport');
    })()`);
    const supplyImage = await page('Page.captureScreenshot', {format:'png'});
    const supplyOutput = path.join(profile, 'opening-supplies.png');
    fs.writeFileSync(supplyOutput, Buffer.from(supplyImage.data, 'base64'));
    console.log('SCREENSHOT: ' + supplyOutput);
    await evaluate(`(async function() {
      $SM.set('features.location.path',true);
      $SM.set('features.location.spaceShip',false);
      $SM.set('game.embarks',1); $SM.set('game.maxDistance',3);
      $SM.set('game.buildings["iron mine"]',0);
      Engine.travelTo(Path);
      await new Promise(resolve => $('#locationSlider').promise().done(resolve));
      $('#journeyGuide').prop('open',true);
      Path.updateJourneyGuide();
      $('#pathScroller, #content, #main, #locationSlider').scrollTop(0);
      window.scrollTo(0,0);
      const guide=document.querySelector('#journeyGuide').getBoundingClientRect();
      const supplies=document.querySelector('#suppliesRow').getBoundingClientRect();
      if (guide.top<0 || guide.right>innerWidth || guide.bottom>supplies.top) throw Error('beginner checklist overlaps supplies or leaves viewport');
    })()`);
    const journeyImage = await page('Page.captureScreenshot', {format:'png'});
    const journeyOutput = path.join(profile, 'beginner-journey.png');
    fs.writeFileSync(journeyOutput, Buffer.from(journeyImage.data, 'base64'));
    console.log('SCREENSHOT: ' + journeyOutput);
    await evaluate(`(async function() {
      ExpeditionReport.show();
      await new Promise(resolve=>Events.eventPanel().promise().done(resolve));
      const title=document.querySelector('.expeditionReport .eventTitle').getBoundingClientRect();
      const close=document.querySelector('#closeExpeditionReport').getBoundingClientRect();
      if(title.top<0 || title.right>innerWidth || close.top<0 || close.bottom>innerHeight) throw Error('expedition report hides its title or close button');
      if(document.querySelectorAll('.expeditionReport strong').length<9) throw Error('expedition key facts are not emphasized');
      if(document.querySelectorAll('.expeditionReport .expeditionSection').length!==4) throw Error('expedition sections missing');
      if(document.querySelector('.expeditionRules').open) throw Error('statistics explanation should start collapsed');
      window.expeditionStateBefore=JSON.stringify({stores:$SM.get('stores'),outfit:Path.outfit,report:ExpeditionReport.latest()});
    })()`);
    await checkDialogTheme('.expeditionReport', false);
    const expeditionImage = await page('Page.captureScreenshot', {format:'png'});
    const expeditionOutput = path.join(profile, 'expedition-report.png');
    fs.writeFileSync(expeditionOutput, Buffer.from(expeditionImage.data, 'base64'));
    console.log('SCREENSHOT: ' + expeditionOutput);
    await checkDialogTheme('.expeditionReport', true);
    const darkExpeditionImage = await page('Page.captureScreenshot', {format:'png'});
    const darkExpeditionOutput = path.join(profile, 'expedition-report-dark.png');
    fs.writeFileSync(darkExpeditionOutput, Buffer.from(darkExpeditionImage.data, 'base64'));
    console.log('SCREENSHOT: ' + darkExpeditionOutput);
    await evaluate(`document.querySelector('.expeditionRules').open=true`);
    await checkDialogTheme('.expeditionReport', true);
    await page('Emulation.setDeviceMetricsOverride', {width:1137,height:745,deviceScaleFactor:1,mobile:false});
    await checkDialogTheme('.expeditionReport', true);
    await page('Emulation.clearDeviceMetricsOverride');
    await checkDialogTheme('.expeditionReport', false);
    await evaluate(`(function(){
      if(JSON.stringify({stores:$SM.get('stores'),outfit:Path.outfit,report:ExpeditionReport.latest()})!==window.expeditionStateBefore) throw Error('reviewing and theme switching must not mutate inventory or report');
    })()`);
    await evaluate(`(async function() {
      await new Promise(resolve=>Events.endEvent(resolve));
      Path.outfit={'nichirin katana':1,'cured meat':5}; $SM.set('outfit',Path.outfit);
      Path.embark();
      await new Promise(resolve=>$('#outerSlider').promise().done(resolve));
      World.curPos=[33,32];World.foodMove=1;World.waterMove=0;World.setWater(2);
      Path.outfit['cured meat']=2;World.updateSupplies();
      World.drawMap();World.updateTravelGuide();
      World.setHp(World.getMaxHealth()-3);
      $('#worldTravelGuide').prop('open',true);
      $('#content, #outerSlider, #worldPanel').scrollTop(0);window.scrollTo(0,0);
      const guide=document.querySelector('#worldTravelGuide').getBoundingClientRect();
      const map=document.querySelector('#map').getBoundingClientRect();
      const treatment=document.querySelector('#worldFieldTreatment').getBoundingClientRect();
      const treatmentButton=document.querySelector('#worldHeal_meat');
      if(guide.top<0 || guide.left<0 || guide.right>innerWidth || guide.bottom>map.top) throw Error('return reminder overlaps map or leaves viewport');
      if(treatment.left<map.right || treatment.right>innerWidth || treatment.top<0 || treatment.bottom>innerHeight) throw Error('field treatment overlaps map or leaves viewport');
      if(Math.abs(treatmentButton.getBoundingClientRect().width-treatment.width)>2) throw Error('field treatment buttons too narrow: '+JSON.stringify({html:treatmentButton.outerHTML,width:getComputedStyle(treatmentButton).width,parentWidth:getComputedStyle(treatmentButton.parentNode).width}));
    })()`);
    const returnImage = await page('Page.captureScreenshot', {format:'png'});
    const returnOutput = path.join(profile, 'world-return-guide.png');
    fs.writeFileSync(returnOutput, Buffer.from(returnImage.data, 'base64'));
    console.log('SCREENSHOT: ' + returnOutput);
    const chapterChecks = await evaluate(`(async function() {
      const checks=[];
      const check=(condition,name)=>{if(!condition) throw Error(name);checks.push(name);};
      const until=async predicate=>{for(let i=0;i<160;i++){if(predicate()) return;await new Promise(resolve=>setTimeout(resolve,30));}throw Error('chapter state did not settle: '+Events.activeScene);};
      World.goHome();
      await new Promise(resolve=>$('#outerSlider').promise().done(resolve));
      $SM.setM('game.buildings',{'iron mine':1,'coal mine':1,steelworks:1});
      const savedMap=$SM.get('game.world.map').map(row=>row.slice());
      savedMap[30][31]='M!';
      $SM.set('game.world.map',savedMap);
      check(savedMap.flat().filter(cell=>cell.charAt(0)==='T').length===1,'world initialization adds exactly one train station');
      check(EarlyGame.milestones().length===20 && EarlyGame.trainReady(),'twenty-stage mainline recognizes safely returned mining and mountain progress');
      $SM.setM('stores',{'nichirin katana':1,'cured meat':20,medicine:5});
      Path.outfit={'nichirin katana':1,'cured meat':5,medicine:2};$SM.set('outfit',Path.outfit);
      check(Path.embark(),'train mission uses a normal charged expedition');
      let station;
      World.state.map.forEach((row,x)=>row.forEach((cell,y)=>{if(cell==='T') station=[x,y];}));
      World.curPos=station;World.drawMap();World.doSpace();
      check(Events.activeEvent()===Events.Setpieces.mugenTrain && !$('#board').hasClass('disabled'),'the real station opens the playable train episode');
      $('#board').trigger('click');$('#defend').trigger('click');
      check(Events.activeScene==='flesh' && $('#enemy').data('hp')===40,'train chapter enters the actual Enmu avatar combat');
      Events.clearTimeouts();
      const originalHit=World.BASE_HIT_CHANCE;World.BASE_HIT_CHANCE=1;
      $('#enemy').data('hp',1);
      $('#attack_nichirin-katana').trigger('click');
      await until(()=>$('#rescue').length && Events.fought);
      World.BASE_HIT_CHANCE=originalHit;
      check(!$SM.get('game.world.mugentrain') && !World.state.mugentrain,'winning the train fight alone does not complete the chapter');
      Button.clearCooldown($('#rescue'));$('#rescue').trigger('click');
      $('#stay').trigger('click');$('#listen').trigger('click');
      check(World.state.mugentrain && !$SM.get('game.world.mugentrain'),'chapter completion remains temporary before return');
      check(Events.eventPanel().text().includes('炎柱') && Events.eventPanel().text().includes('安全返回庄园'),'train ending explains lore and safe-return requirement');
      await new Promise(resolve=>Events.endEvent(resolve));

      // Ordinary victory: real attack, live discard counts, and treatment before exit.
      Path.outfit={'nichirin katana':1,medicine:3,'cured meat':Path.getCapacity()-Path.getWeight('nichirin katana')-3*Path.getWeight('medicine')};
      World.setHp(World.getMaxHealth()-5);
      Events.startEvent({title:'战后收拾背包',scenes:{start:{combat:true,enemy:'blood mist demon',chara:'鬼',health:1,damage:1,hit:1,attackDelay:30,loot:{cloth:{min:4,max:5,chance:1}},deathMessage:'鬼已倒下。'}}});
      Events.clearTimeouts();World.BASE_HIT_CHANCE=1;
      $('#attack_nichirin-katana').trigger('click');
      await until(()=>$('#leaveBtn').length && Events.fought);
      World.BASE_HIT_CHANCE=originalHit;
      check($('#buttons').children().last().attr('id')==='exitButtons','ordinary victory leaves treatment above the final exit');
      const food=Path.outfit['cured meat'];
      Events.drawDrop($('#take_cloth'));
      check($('#drop_cured-meat').text().includes('背包 '+food) && $('#drop_medicine').text().includes('背包 3'),'actual discard menu shows every remaining backpack quantity');
      $('#drop_cured-meat').trigger('click');
      check(Path.outfit['cured meat']===food-1 && Path.outfit.cloth===1 && $('#drop_cured-meat').text().includes('背包 '+(food-1)),'discarding and pickup refresh quantities without reopening');
      $('#dropMenu').remove();
      document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'2',bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup',{key:'2',bubbles:true}));
      check(Path.outfit.medicine===2,'reordered post-battle treatment preserves the medicine hotkey');
      Button.clearCooldown($('#leaveBtn'));$('#leaveBtn').trigger('click');
      await until(()=>!Events.activeEvent());
      check(World.goHome() && $SM.get('game.world.mugentrain'),'safe return commits the new train chapter');
      check(ExpeditionReport.latest().unlocks.includes('无限列车支援完成'),'expedition report includes the new chapter completion');
      return checks;
    })()`);
    console.log(chapterChecks.map(name=>'PASS: '+name).join('\n'));
    const noticeChecks = await evaluate(`(async function() {
      const checks = [];
      const check = (condition, name) => { if (!condition) throw Error(name); checks.push(name); };
      await new Promise(resolve => $('#outerSlider').promise().done(resolve));
      check(!Events.activeEvent(), 'completed journey leaves no event before notice reading');
      const before = JSON.stringify(State), outfitBefore = JSON.stringify(Path.outfit);
      $('.menuToggle').trigger('click');
      check($('#updateNotesButton').is(':visible'), 'update announcement button is available in the menu');
      $('#updateNotesButton').trigger('click');
      const event = Events.activeEvent(), panel = Events.eventPanel();
      check(panel.hasClass('updateNotes') && panel.attr('role') === 'dialog', 'menu opens the actual update announcement dialog');
      check(panel.find('.updateNotesEntry').length === UpdateNotes.entries.length && panel.find('.updateNotesEntry[open]').length === 1, 'recent history starts with the latest batch expanded and older batches collapsed');
      check(panel.text().includes('20 个阶段') && panel.text().includes('150 → 15') && panel.text().includes('2 个肉 + 5 块木头'), 'recent mainline and resource changes are included in the game announcement');
      check(panel.find('li strong').length > 50, 'important update labels are bold throughout the history');
      $('#expandUpdateNotes').trigger('click');
      check(panel.find('.updateNotesEntry[open]').length === UpdateNotes.entries.length, 'all historical announcement batches can be expanded');
      $('#updateNotesCategory').val('资源').trigger('change');
      check(panel.find('li').length === UpdateNotes.filteredEntries('资源').reduce((sum, entry) => sum + entry.items.length, 0) && !panel.text().includes('菜单更新公告：'), 'category filtering displays only matching update items');
      $('#updateNotesCategory').val('全部').trigger('change');
      $('#collapseUpdateNotes').trigger('click');
      check(panel.find('.updateNotesEntry[open]').length === 1, 'collapse history keeps the latest announcement readable');
      check(!UpdateNotes.show() && Events.activeEvent() === event, 'opening twice never replaces or stacks the announcement');
      document.body.dispatchEvent(new KeyboardEvent('keydown', {key:'1', bubbles:true}));
      document.body.dispatchEvent(new KeyboardEvent('keyup', {key:'1', bubbles:true}));
      check(JSON.stringify(State) === before && JSON.stringify(Path.outfit) === outfitBefore, 'reading and filtering announcements never change saves or use background supplies');
      return checks;
    })()`);
    console.log(noticeChecks.map(name => 'PASS: ' + name).join('\n'));
    await checkDialogTheme('.eventPanel.updateNotes', false);
    const noticeDay = await page('Page.captureScreenshot', {format:'png'});
    fs.writeFileSync(path.join(profile, 'update-notes.png'), Buffer.from(noticeDay.data, 'base64'));
    console.log('SCREENSHOT: ' + path.join(profile, 'update-notes.png'));
    await checkDialogTheme('.eventPanel.updateNotes', true);
    const noticeDark = await page('Page.captureScreenshot', {format:'png'});
    fs.writeFileSync(path.join(profile, 'update-notes-dark.png'), Buffer.from(noticeDark.data, 'base64'));
    console.log('SCREENSHOT: ' + path.join(profile, 'update-notes-dark.png'));
    await evaluate(`(async function() {
      document.querySelector('#closeUpdateNotes').dispatchEvent(new KeyboardEvent('keydown', {key:'Escape', bubbles:true}));
      for (let i=0; i<50 && Events.activeEvent(); i++) await new Promise(resolve => setTimeout(resolve,20));
      if (Events.activeEvent() || document.activeElement.id !== 'updateNotesButton') throw Error('Escape must close notices and restore menu focus');
      const menu=document.querySelector('.menu'), button=document.querySelector('#updateNotesButton');
      for(let i=0;i<40 && button.getBoundingClientRect().top<menu.getBoundingClientRect().top;i++) await new Promise(resolve=>setTimeout(resolve,25));
      if(button.getBoundingClientRect().top<menu.getBoundingClientRect().top) throw Error('restored announcement focus must stay visible in the expanded menu');
      const module = Engine.activeModule, before = JSON.stringify(State);
      Engine.activeModule = World;
      if (UpdateNotes.show() || Events.activeEvent()) throw Error('notice must never pause world exploration');
      Engine.activeModule = Space;
      if (UpdateNotes.show() || Events.activeEvent()) throw Error('notice must never pause castle exploration');
      Engine.activeModule = module;
      if (JSON.stringify(State) !== before) throw Error('blocked notice changed persistent state');
    })()`);
    console.log('PASS: notice Escape restores focus, and active exploration cannot open a pause-like announcement.');
    const scrapChecks = await evaluate(`(function() {
      const checks = [], check = (condition, name) => { if (!condition) throw Error(name); checks.push(name); };
      $SM.set('stores["bone yari"]',8);
      Path.outfit['bone yari']=1; $SM.set('outfit',Path.outfit);
      Path.updateOutfitting();
      const trigger = $('#outfit_bone-yari > .scrapBtn')[0] || $('#outfitting .outfitRow[key="bone yari"] > .scrapBtn')[0];
      check(!!trigger,'recycling row exposes the live Shift-click preview');
      const before = JSON.stringify(State);
      trigger.dispatchEvent(new MouseEvent('click',{shiftKey:true,bubbles:true}));
      check($('#scrapQuantityPanel').attr('role')==='dialog' && $('.scrapQuantityStock').text().includes('背包保护1'), 'real Shift-click opens recycling preview with packed inventory protected');
      $('#scrapQuantityInput').val('3').trigger('input');
      check($('#scrapQuantityRefund').text().includes('+90') && $('#scrapQuantityRefund').text().includes('+4'), 'real batch preview uses whole-batch material rounding');
      check(JSON.stringify(State)===before,'editing recycling preview does not change saves');
      $('#scrapQuantityInput').val('1.5').trigger('input');
      check($('.scrapQuantityOk').prop('disabled') && !$('#scrapQuantityRefund').text(), 'fractional recycling quantities disable confirmation and hide misleading refunds');
      $('#scrapQuantityInput').val('3').trigger('input');
      $SM.set('stores["bone yari"]',2);
      check($('.scrapQuantityOk').prop('disabled') && $('.scrapQuantityStock').text().includes('可回收1'), 'stock changes refresh the open preview without silently shrinking the selected amount');
      $SM.set('stores["bone yari"]',6);
      check(!$('.scrapQuantityOk').prop('disabled'),'restocking restores a valid batch confirmation');
      let backgroundClicks=0;
      const background=$('<button>').attr({'data-hotkey':'1',id:'backgroundPreviewTest'}).text('test').on('click',()=>backgroundClicks++).appendTo('body');
      $('.scrapQuantityOk').trigger('focus');
      document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'1',bubbles:true}));
      document.activeElement.dispatchEvent(new KeyboardEvent('keyup',{key:'1',bubbles:true}));
      check(backgroundClicks===0,'quantity dialog blocks background hotkeys even when focus is on its confirmation button');
      const module=Engine.activeModule;
      document.activeElement.dispatchEvent(new KeyboardEvent('keyup',{key:'a',keyCode:65,which:65,bubbles:true}));
      check(Engine.activeModule===module,'quantity dialog also prevents key-release navigation behind it');
      background.remove();
      const wood=$SM.get('stores.wood'),teeth=$SM.get('stores.teeth');
      $('.scrapQuantityOk').trigger('click');
      check($SM.get('stores["bone yari"]')===3 && Path.outfit['bone yari']===1 && $SM.get('stores.wood')===wood+90 && $SM.get('stores.teeth')===teeth+4, 'confirmed recycling charges the exact batch and preserves packed copies');
      check(!$('#scrapQuantityOverlay').length && document.activeElement===trigger,'successful recycling closes preview and restores the triggering button');
      trigger.dispatchEvent(new MouseEvent('click',{shiftKey:true,bubbles:true}));
      $('#scrapQuantityInput').val('1').trigger('input');
      return checks;
    })()`);
    console.log(scrapChecks.map(name=>'PASS: '+name).join('\n'));
    const checkScrapTheme = dark => evaluate('(' + (async function(dark) {
      if (Engine.isLightsOff()!==dark) Engine.turnLightsOff();
      const panel=document.querySelector('#scrapQuantityPanel'), expected=dark?'rgb(39, 40, 35)':'rgb(255, 255, 255)';
      for(let i=0;i<40 && getComputedStyle(panel).backgroundColor!==expected;i++) await new Promise(resolve=>setTimeout(resolve,25));
      if(getComputedStyle(panel).backgroundColor!==expected) throw Error('recycling theme incorrect');
      const box=panel.getBoundingClientRect();
      if(box.top<0 || box.bottom>innerHeight) throw Error('recycling controls outside viewport');
    }).toString()+')('+dark+')');
    await checkScrapTheme(false);
    const scrapDay=await page('Page.captureScreenshot',{format:'png'});
    fs.writeFileSync(path.join(profile,'scrap-preview.png'),Buffer.from(scrapDay.data,'base64'));
    console.log('SCREENSHOT: '+path.join(profile,'scrap-preview.png'));
    await checkScrapTheme(true);
    const scrapDark=await page('Page.captureScreenshot',{format:'png'});
    fs.writeFileSync(path.join(profile,'scrap-preview-dark.png'),Buffer.from(scrapDark.data,'base64'));
    console.log('SCREENSHOT: '+path.join(profile,'scrap-preview-dark.png'));
    await evaluate(`(function() {
      const before=JSON.stringify(State),trigger=Path._scrapDialog.trigger;
      document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
      if($('#scrapQuantityOverlay').length || JSON.stringify(State)!==before || document.activeElement!==trigger) throw Error('cancelled recycling must not charge and must restore focus');
    })()`);
    console.log('PASS: actual recycling Escape cancels without consuming items.');
    assert.deepEqual(errors, [], 'uncaught browser exceptions');
  } finally {
    if (call && socket?.readyState === WebSocket.OPEN) {
      try { await call('Browser.close'); } catch {}
    }
    socket?.close();
    browser.kill();
    server.closeAllConnections();
    server.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
