const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const c = {_: (s,...args)=>s.replace(/\{(\d+)\}/g,(_,n)=>args[n])};
vm.createContext(c);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../script/camp_guide.js'),'utf8'),c);
const guide=c.CampGuide;
const defs={fast:{damage:5,cooldown:1,cost:{ammo:2}},slow:{damage:15,cooldown:5,cost:{slow:1}},bind:{damage:'stun',cooldown:15}};
const slots=['fast','slow'];
let preview=guide.weaponPreview('fast',slots,1,defs,{ammo:5});
assert.equal(preview.shared,1,'moving an already-equipped weapon clears its previous slot');
assert.equal(preview.uses,2);
assert.deepEqual(slots,['fast','slow'],'preview never mutates equipment');
preview=guide.weaponPreview('fast',slots,0,defs,{});
assert.equal(preview.cooldown,1);
assert.equal(preview.shared,5,'own cooldown and other-slot shared cooldown are different');
assert.equal(preview.uses,0);
assert.equal(guide.weaponPreview('bind',[null,null],0,defs,{}).damage,'stun');
assert.equal(guide.weaponPreview('bind',[null,null],0,defs,{}).uses,null);
assert.equal(guide.weaponPreview('unknown',slots,0,defs,{}),null);
const income={gatherer:{delay:10,stores:{wood:3}},charcutier:{delay:10,stores:{wood:-10,meat:-10,'cured meat':2}},hunter:{delay:10,stores:{meat:0.5,fur:0.5}}};
const stores={wood:100,meat:5};
const snapshot=JSON.stringify({income,stores});
let r=guide.production(income,stores);
assert.equal(r.rows[1].missing.length,1);
assert.equal(r.rows[1].missing[0].item,'meat');
assert.equal(r.rows[1].missing[0].amount,10);
assert.equal(r.net.wood,-42);
assert.equal(r.net.meat,-57);
assert.equal(r.net.fur,3);
assert.equal(JSON.stringify({income,stores}),snapshot,'diagnostics never alter production');
stores.meat=10;assert.equal(guide.production(income,stores).rows[1].missing.length,0);
assert.equal(guide.production({idle:{delay:10,stores:{wood:0}},bad:{delay:0,stores:{wood:1}}},{}).rows.length,0);
const weapons={sword:{damage:3},gun:{damage:5,cost:{ammo:2}},bind:{damage:'stun',cost:{bind:1}}};
const check=(outfit,stock,eq=['sword'],cap=30,tester=false)=>guide.expedition(outfit,stock,eq,weapons,cap,()=>1,tester);
r=check({'cured meat':5,sword:1},{'cured meat':5,sword:1});
assert.equal(r.errors.length,0);assert.equal(r.warnings.length,0);
assert.equal(check({'cured meat':1},{'cured meat':1},[]).warnings.length,2);
assert.ok(check({'cured meat':5,gun:1,ammo:1},{'cured meat':5,gun:1,ammo:1},['gun']).warnings.some(s=>s.includes('ammunition')));
assert.equal(check({'cured meat':5,gun:1,ammo:2},{'cured meat':5,gun:1,ammo:2},['gun']).ready.length,1);
assert.equal(check({'cured meat':5,bind:1},{'cured meat':5,bind:1},['bind']).ready.length,0);
assert.ok(check({'cured meat':5,sword:1},{'cured meat':4,sword:1}).errors.length);
for (const n of [-1,1.5,NaN,Infinity,'1']) assert.ok(check({'cured meat':5,sword:n},{'cured meat':5,sword:10}).errors.length);
assert.ok(check({'cured meat':5},{'cured meat':5},[],4).errors.length);
assert.ok(check({},{}).errors.length);
assert.equal(check({'cured meat':5,sword:1},{},['sword'],30,true).errors.length,0);
console.log('PASS: group batch shortages, fractional rates, theoretical net flow, read-only diagnostics, expedition stock/capacity/ammunition and tester validation.');
